"""initial

Revision ID: 7b8618a72ca3
Revises: 
Create Date: 2026-05-28 23:28:59.349915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b8618a72ca3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Shared ordering sequence used by aistudiobot_chathistory.seq +
    # aistudiobot_agent_actions.seq. Alembic autogen doesn't reliably emit
    # CREATE SEQUENCE for column-default Sequence() objects; create it here
    # so the `nextval(...)` defaults below resolve.
    op.execute("CREATE SEQUENCE IF NOT EXISTS aistudiobot_event_seq")
    op.create_table('aistudiobot_agent_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_message_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.BigInteger(), server_default=sa.text("nextval('aistudiobot_event_seq')"), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('tool_kind', sa.String(length=32), nullable=True),
    sa.Column('call_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aistudiobot_agent_actions'))
    )
    op.create_index(op.f('ix_aistudiobot_agent_actions_chat_conversation_id'), 'aistudiobot_agent_actions', ['chat_conversation_id'], unique=False)
    op.create_index(op.f('ix_aistudiobot_agent_actions_user_message_id'), 'aistudiobot_agent_actions', ['user_message_id'], unique=False)
    op.create_table('aistudiobot_agent_checkpoint',
    sa.Column('checkpoint_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_name', sa.String(length=256), nullable=False),
    sa.Column('graph_signature_hash', sa.String(length=128), nullable=False),
    sa.Column('previous_checkpoint_id', sa.String(length=64), nullable=True),
    sa.Column('chat_conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('iteration_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('version', sa.String(length=16), server_default=sa.text("'1.0'"), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_floor', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('checkpoint_id', name=op.f('pk_aistudiobot_agent_checkpoint'))
    )
    op.create_index(op.f('ix_aistudiobot_agent_checkpoint_chat_conversation_id'), 'aistudiobot_agent_checkpoint', ['chat_conversation_id'], unique=False)
    op.create_index('ix_aistudiobot_agent_checkpoint_name_ts', 'aistudiobot_agent_checkpoint', ['workflow_name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_aistudiobot_agent_checkpoint_workflow_name'), 'aistudiobot_agent_checkpoint', ['workflow_name'], unique=False)
    op.create_table('aistudiobot_agent_human_input',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_message_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('function_name', sa.String(length=128), nullable=True),
    sa.Column('call_id', sa.String(length=128), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_type', sa.String(length=256), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'open'"), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aistudiobot_agent_human_input')),
    sa.UniqueConstraint('chat_conversation_id', 'request_id', name='uq_aistudiobot_agent_human_input_conv_request')
    )
    op.create_index(op.f('ix_aistudiobot_agent_human_input_chat_conversation_id'), 'aistudiobot_agent_human_input', ['chat_conversation_id'], unique=False)
    op.create_index('ix_aistudiobot_agent_human_input_open', 'aistudiobot_agent_human_input', ['chat_conversation_id'], unique=False, postgresql_where=sa.text("status = 'open'"))
    op.create_index(op.f('ix_aistudiobot_agent_human_input_user_message_id'), 'aistudiobot_agent_human_input', ['user_message_id'], unique=False)
    op.create_table('aistudiobot_agent_llm_call',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_message_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aistudiobot_agent_llm_call'))
    )
    op.create_index(op.f('ix_aistudiobot_agent_llm_call_chat_conversation_id'), 'aistudiobot_agent_llm_call', ['chat_conversation_id'], unique=False)
    op.create_index(op.f('ix_aistudiobot_agent_llm_call_user_message_id'), 'aistudiobot_agent_llm_call', ['user_message_id'], unique=False)
    op.create_table('aistudiobot_bot',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aistudiobot_bot'))
    )
    op.create_table('aistudiobot_channel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aistudiobot_channel'))
    )
    op.create_table('aistudiobot_store',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_aistudiobot_store'))
    )
    op.create_table('aistudiobot_botchannelmapping',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['aistudiobot_bot.id'], name=op.f('fk_aistudiobot_botchannelmapping_bot_id_aistudiobot_bot')),
    sa.ForeignKeyConstraint(['channel_id'], ['aistudiobot_channel.id'], name=op.f('fk_aistudiobot_botchannelmapping_channel_id_aistudiobot_channel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aistudiobot_botchannelmapping'))
    )
    op.create_table('aistudiobot_chatsession',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_conversation_id', sa.String(length=150), nullable=False),
    sa.Column('agent_channel_mapping_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['agent_channel_mapping_id'], ['aistudiobot_botchannelmapping.id'], name=op.f('fk_aistudiobot_chatsession_agent_channel_mapping_id_aistudiobot_botchannelmapping')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aistudiobot_chatsession'))
    )
    op.create_table('aistudiobot_chatconversation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('is_ka', sa.Boolean(), nullable=False),
    sa.Column('chat_session_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['aistudiobot_chatsession.id'], name=op.f('fk_aistudiobot_chatconversation_chat_session_id_aistudiobot_chatsession')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aistudiobot_chatconversation'))
    )
    op.create_table('aistudiobot_chathistory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('message_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chat_conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_session_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('seq', sa.BigInteger(), server_default=sa.text("nextval('aistudiobot_event_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['chat_conversation_id'], ['aistudiobot_chatconversation.id'], name=op.f('fk_aistudiobot_chathistory_chat_conversation_id_aistudiobot_chatconversation')),
    sa.ForeignKeyConstraint(['chat_session_id'], ['aistudiobot_chatsession.id'], name=op.f('fk_aistudiobot_chathistory_chat_session_id_aistudiobot_chatsession')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aistudiobot_chathistory'))
    )
    op.create_index(op.f('ix_aistudiobot_chathistory_chat_conversation_id'), 'aistudiobot_chathistory', ['chat_conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aistudiobot_chathistory_chat_conversation_id'), table_name='aistudiobot_chathistory')
    op.drop_table('aistudiobot_chathistory')
    op.drop_table('aistudiobot_chatconversation')
    op.drop_table('aistudiobot_chatsession')
    op.drop_table('aistudiobot_botchannelmapping')
    op.drop_table('aistudiobot_store')
    op.drop_table('aistudiobot_channel')
    op.drop_table('aistudiobot_bot')
    op.drop_index(op.f('ix_aistudiobot_agent_llm_call_user_message_id'), table_name='aistudiobot_agent_llm_call')
    op.drop_index(op.f('ix_aistudiobot_agent_llm_call_chat_conversation_id'), table_name='aistudiobot_agent_llm_call')
    op.drop_table('aistudiobot_agent_llm_call')
    op.drop_index(op.f('ix_aistudiobot_agent_human_input_user_message_id'), table_name='aistudiobot_agent_human_input')
    op.drop_index('ix_aistudiobot_agent_human_input_open', table_name='aistudiobot_agent_human_input', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_aistudiobot_agent_human_input_chat_conversation_id'), table_name='aistudiobot_agent_human_input')
    op.drop_table('aistudiobot_agent_human_input')
    op.drop_index(op.f('ix_aistudiobot_agent_checkpoint_workflow_name'), table_name='aistudiobot_agent_checkpoint')
    op.drop_index('ix_aistudiobot_agent_checkpoint_name_ts', table_name='aistudiobot_agent_checkpoint')
    op.drop_index(op.f('ix_aistudiobot_agent_checkpoint_chat_conversation_id'), table_name='aistudiobot_agent_checkpoint')
    op.drop_table('aistudiobot_agent_checkpoint')
    op.drop_index(op.f('ix_aistudiobot_agent_actions_user_message_id'), table_name='aistudiobot_agent_actions')
    op.drop_index(op.f('ix_aistudiobot_agent_actions_chat_conversation_id'), table_name='aistudiobot_agent_actions')
    op.drop_table('aistudiobot_agent_actions')
    op.execute("DROP SEQUENCE IF EXISTS aistudiobot_event_seq")
    # ### end Alembic commands ###
